"""Organization planning for Project Hygiene Review."""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

from code_review_agent.hygiene.classifier import (
    ARTIFACT,
    DATA_SCRIPT,
    DESIGN_DOC,
    DEV_SCRIPT,
    EXPERIMENT,
    PLANNING_DOC,
    RESEARCH_DOC,
    TODO,
    UNKNOWN,
)
from code_review_agent.hygiene.taxonomy import MOVE_TYPES, TARGET_DIRS as SEMANTIC_TARGET_DIRS
from code_review_agent.models import FileClassification, MoveSuggestion, SemanticClassification


CATEGORY_TARGET_DIRS = {
    DATA_SCRIPT: "scripts/data",
    DEV_SCRIPT: "scripts/dev",
    EXPERIMENT: "scripts/experiments",
    DESIGN_DOC: "docs/design",
    RESEARCH_DOC: "docs/research",
    PLANNING_DOC: "docs/planning",
    TODO: "docs/planning",
    ARTIFACT: "artifacts/reports",
}


def build_move_suggestions(
    repo_path: Path | str,
    classifications: list[FileClassification],
) -> list[MoveSuggestion]:
    """Build safe move suggestions without touching repository files."""

    root = Path(repo_path)
    used_targets = {classification.path for classification in classifications}
    suggestions: list[MoveSuggestion] = []

    for classification in classifications:
        target_dir = CATEGORY_TARGET_DIRS.get(classification.category)
        if not target_dir:
            continue
        if classification.mainline_relevance == "high":
            continue

        source = Path(classification.path)
        suggested = Path(target_dir) / source.name
        if source.as_posix() == suggested.as_posix():
            continue

        safe_target = _deduplicate_target(root, suggested, used_targets)
        used_targets.add(safe_target)
        suggestions.append(
            MoveSuggestion(
                source_path=classification.path,
                suggested_path=safe_target,
                category=classification.category,
                reason=classification.reason,
                confidence=classification.confidence,
            )
        )

    return sorted(suggestions, key=lambda item: item.source_path)


def build_project_artifacts_draft(
    classifications: list[FileClassification],
    suggestions: list[MoveSuggestion],
) -> str:
    """Render a PROJECT_ARTIFACTS.md draft for human review."""

    suggestion_by_source = {
        suggestion.source_path: suggestion
        for suggestion in suggestions
    }
    grouped: dict[str, list[FileClassification]] = defaultdict(list)
    for classification in classifications:
        if classification.category in CATEGORY_TARGET_DIRS or classification.category == UNKNOWN:
            grouped[classification.category].append(classification)

    lines = [
        "# Project Artifacts",
        "",
        "> Draft generated by Project Hygiene Review. Review before moving files.",
        "",
    ]

    if not grouped:
        lines.extend(["No project artifacts were detected.", ""])
        return "\n".join(lines)

    for category in sorted(grouped):
        lines.extend([f"## {category}", ""])
        lines.append("| Original Path | Suggested Location | Confidence | Notes |")
        lines.append("|---|---|---:|---|")
        for classification in sorted(grouped[category], key=lambda item: item.path):
            suggestion = suggestion_by_source.get(classification.path)
            suggested_path = suggestion.suggested_path if suggestion else ""
            notes = _escape_table_text(classification.reason)
            lines.append(
                "| "
                f"`{classification.path}` | "
                f"`{suggested_path}` | "
                f"{classification.confidence:.2f} | "
                f"{notes} |"
            )
        lines.append("")

    return "\n".join(lines)


def _deduplicate_target(
    repo_path: Path,
    target: Path,
    used_targets: set[str],
) -> str:
    candidate = target.as_posix()
    if candidate not in used_targets and not (repo_path / target).exists():
        return candidate

    stem = target.stem
    suffix = target.suffix
    parent = target.parent
    counter = 2
    while True:
        candidate_path = parent / f"{stem}_{counter}{suffix}"
        candidate = candidate_path.as_posix()
        if candidate not in used_targets and not (repo_path / candidate_path).exists():
            return candidate
        counter += 1


def _escape_table_text(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


# ---------------------------------------------------------------------------
# Semantic planner helpers
# ---------------------------------------------------------------------------


def build_move_suggestions_from_semantic(
    repo_path: Path | str,
    semantic_classifications: list[SemanticClassification],
    *,
    confidence_threshold: float = 0.6,
) -> list[MoveSuggestion]:
    """Build move suggestions from LLM semantic classifications.

    Only generates suggestions for:
    - ``artifact_type`` in :data:`~code_review_agent.hygiene.taxonomy.MOVE_TYPES`.
    - ``confidence >= confidence_threshold``.
    - ``suggested_action != 'needs_human_review'``.
    """
    root = Path(repo_path)
    used_targets: set[str] = {sc.path for sc in semantic_classifications}
    suggestions: list[MoveSuggestion] = []

    for sc in semantic_classifications:
        if sc.artifact_type not in MOVE_TYPES:
            continue
        if sc.confidence < confidence_threshold:
            continue
        if sc.suggested_action == "needs_human_review":
            continue

        target_dir = SEMANTIC_TARGET_DIRS.get(sc.artifact_type)
        if not target_dir:
            continue

        source = Path(sc.path)
        suggested = Path(target_dir) / source.name
        if source.as_posix() == suggested.as_posix():
            continue

        safe_target = _deduplicate_target(root, suggested, used_targets)
        used_targets.add(safe_target)
        suggestions.append(
            MoveSuggestion(
                source_path=sc.path,
                suggested_path=safe_target,
                category=sc.artifact_type,
                reason=sc.reason,
                confidence=sc.confidence,
            )
        )

    return sorted(suggestions, key=lambda s: s.source_path)


def build_uncertain_queue(
    semantic_classifications: list[SemanticClassification],
) -> list[SemanticClassification]:
    """Return all files that need human review (uncertain or obsolete)."""
    return [
        sc for sc in semantic_classifications
        if sc.suggested_action == "needs_human_review"
    ]
