"""Taxonomy for process artifact semantic classification.

Defines 7 stable artifact types that an LLM classifier must choose from.
The taxonomy is intentionally small so LLM boundaries stay clear and
unit tests can cover every type without combinatorial explosion.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Type constants
# ---------------------------------------------------------------------------

EXPERIMENT_SCRIPT = "experiment_script"
ADHOC_SCRIPT = "adhoc_script"
PROCESS_DOC = "process_doc"
GENERATED_ARTIFACT = "generated_artifact"
DEMO_SAMPLE = "demo_sample"
OBSOLETE_CANDIDATE = "obsolete_candidate"
UNCERTAIN = "uncertain"

ALL_TYPES: frozenset[str] = frozenset(
    {
        EXPERIMENT_SCRIPT,
        ADHOC_SCRIPT,
        PROCESS_DOC,
        GENERATED_ARTIFACT,
        DEMO_SAMPLE,
        OBSOLETE_CANDIDATE,
        UNCERTAIN,
    }
)

# Types that warrant a concrete move suggestion (high confidence only).
MOVE_TYPES: frozenset[str] = frozenset(
    {
        EXPERIMENT_SCRIPT,
        ADHOC_SCRIPT,
        PROCESS_DOC,
        GENERATED_ARTIFACT,
        DEMO_SAMPLE,
    }
)

# Types that should go to the human-review queue instead.
REVIEW_TYPES: frozenset[str] = frozenset({OBSOLETE_CANDIDATE, UNCERTAIN})

# ---------------------------------------------------------------------------
# Actions & target directories
# ---------------------------------------------------------------------------

SUGGESTED_ACTIONS: dict[str, str] = {
    EXPERIMENT_SCRIPT: "move",
    ADHOC_SCRIPT: "move",
    PROCESS_DOC: "move",
    GENERATED_ARTIFACT: "move",
    DEMO_SAMPLE: "document",
    OBSOLETE_CANDIDATE: "needs_human_review",
    UNCERTAIN: "needs_human_review",
}

TARGET_DIRS: dict[str, str] = {
    EXPERIMENT_SCRIPT: "scripts/experiments",
    ADHOC_SCRIPT: "scripts/adhoc",
    PROCESS_DOC: "docs/process",
    GENERATED_ARTIFACT: "artifacts",
    DEMO_SAMPLE: "examples",
    # OBSOLETE_CANDIDATE and UNCERTAIN have no default target dir.
}

# ---------------------------------------------------------------------------
# LLM-facing descriptions
# ---------------------------------------------------------------------------

DESCRIPTIONS: dict[str, str] = {
    EXPERIMENT_SCRIPT: (
        "A script used for prompt testing, strategy experiments, or one-off validation. "
        "Typical signals: filename contains 'experiment', 'prompt', 'test_v', 'scratch', "
        "or content contains LLM prompt strings, eval loops, or throwaway __main__ blocks."
    ),
    ADHOC_SCRIPT: (
        "A one-off helper script for data download, data cleanup, migration, or manual debugging. "
        "Typical signals: filename contains 'download', 'fetch', 'clean', 'migrate', 'debug', "
        "or content uses pandas, requests, subprocess heavily with no formal entry point."
    ),
    PROCESS_DOC: (
        "A document capturing planning notes, research findings, TODO lists, or phase records. "
        "Typical signals: filename is TODO.md, NOTES.md, ROADMAP.md, or content has '- [ ]' "
        "task lists, or section headers like '## Phase', '## Plan', '## Research'."
    ),
    GENERATED_ARTIFACT: (
        "A file generated by a tool run, such as a report, benchmark output, or snapshot. "
        "Typical signals: lives under outputs/, reports/, artifacts/, or filename contains "
        "'report', 'result', 'output', 'snapshot', 'benchmark'."
    ),
    DEMO_SAMPLE: (
        "A demo, walkthrough script, or example file intended for demonstration, not production. "
        "Typical signals: filename contains 'demo', 'example', 'sample', or lives under examples/."
    ),
    OBSOLETE_CANDIDATE: (
        "A file that once appeared to be mainline code but currently has no imports, no test "
        "references, no config declarations, and no clear entry point. May be dead code."
    ),
    UNCERTAIN: (
        "Evidence is insufficient to determine whether the file is a process artifact or mainline "
        "code. Requires human review before any action is taken."
    ),
}
